# Generated by Django 5.1.6 on 2025-04-10 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('video_url', models.URLField(verbose_name='Video URL')),
                ('thumbnail_url', models.URLField(blank=True, verbose_name='Thumbnail URL')),
                ('expert_tips', models.TextField(blank=True, verbose_name='Expert Tips')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'News Video',
                'verbose_name_plural': 'News Videos',
                'ordering': ['-created_at'],
            },
        ),
    ]
