# Generated by Django 5.1.6 on 2025-04-10 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsvideo',
            options={'ordering': ['display_order', '-created_at'], 'verbose_name': 'News Video', 'verbose_name_plural': 'News Videos'},
        ),
        migrations.AddField(
            model_name='newsvideo',
            name='display_order',
            field=models.IntegerField(default=0, verbose_name='Display Order'),
        ),
    ]
