# Generated by Django 5.1.6 on 2025-04-07 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='gender_icon',
            field=models.ImageField(blank=True, null=True, upload_to='gender_icons/'),
        ),
    ]
