# Generated by Django 5.1.6 on 2025-04-07 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_healthdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthdata',
            name='emergency_contact',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='healthdata',
            name='height',
            field=models.PositiveIntegerField(blank=True, help_text='Height in centimeters', null=True),
        ),
        migrations.AlterField(
            model_name='healthdata',
            name='weight',
            field=models.PositiveIntegerField(blank=True, help_text='Weight in kilograms', null=True),
        ),
    ]
