# Generated by Django 5.1.6 on 2025-04-10 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_usersession'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserSession',
        ),
    ]
