# Generated by Django 5.1.6 on 2025-05-06 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_userprofile_failed_login_attempts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='alert_cooldown_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='alert_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_alert_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_failed_attempt',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
